# Site settings
title: Wedding!
email: wedding@hollyandandrew.co.uk
url: http://hollyandandrew.co.uk
description: "Holly Phillips and Andrew Miller are getting Married!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#F9EACC'
  # primary-dark: '#F4E2BE'
  links: '#62892A'

# Footer settings
footer: Holly & Andy

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url: https://facebook.com

page-sections:
    - name: register
      menu: true
    - name: how_long
      menu: true
      title: How Long?
    - name: contact
      menu: true
    - name: map
      menu: false

# Build settings
markdown: kramdown
permalink: pretty
